# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Julian Ing's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Julian Ing
#headline: headline message
description: >- # dont remove this line. this will ignore all new lines until the next section
  I'm a robotics engineer driven by a deep passion for the intersection of biology and technology. For the past eight years, 
  I’ve been fascinated by how robotics can augment human capabilities, a journey inspired by my close relationship with an above-knee amputee. 
  This personal connection has shaped not just my interests but my purpose: to develop technologies that genuinely improve lives. <br> 
  My academic and professional path reflects this mission. I hold a Master’s degree in 'Human and Biological Robotics' from 
  Imperial College London, where I designed and developed a dexterous robotic hand as part of my thesis; a project many thought 
  impossible due to its complexity, yet I completed it solo within five months on a tight budget. Before that, I earned a 
  First-Class Honours degree in Robotics from Middlesex University, where I developed a brain-computer interface to control a 
  robotic arm with my thoughts. <br>
  My work blends mechanical design, programming, and human-centered engineering, with a focus on assistive technologies like prosthetics and exoskeletons. Beyond robotics, I’ve run a successful clothing brand, giving me unique expertise in textiles—an unexpected but valuable asset when considering ergonomics and wearable tech.
  This portfolio showcases my projects, skills, and the journey I’ve taken to merge technology with humanity. <br>
  For me, engineering isn’t just a career; it’s a way to contribute meaningfully to the world.
  

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/profile2.png


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/1dbIJqO5nyMErvAaarNkwfCvBSomGqYos/view?usp=sharing


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: julian-ing    # https://www.linkedin.com/in/{your url slug} 
  github:     # https://github.com/{your url slug} 
  stackoverflow:       # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

skills:
  - category: Robotics Engineering
    tools:
      - Dexterous Robotic Hand Design
      - In-Hand Manipulation
      - Anthropomorphic Robotics
      - Prosthetic Development
      - Biologically Inspired Robotics

  - category: Mechanical Design
    tools:
      - SolidWorks (CAD)
      - Finite Element Analysis (FEA)
      - Linkage Mechanism Design
      - Mechanical Simulation
      - 3D Printing (PolyJet, FDM)
      - CNC Machining

  - category: Electronics & Embedded Systems
    tools:
      - Microcontroller Programming (Arduino, STM32)
      - Motor Control (DC Motors, Encoders, Motor Drivers)
      - PCB Design and Circuit Prototyping
      - Power Management Systems

  - category: Programming & Software Development
    tools:
      - Python (Primary Language)
      - C++ (Robotics Applications)
      - MATLAB (Signal Processing)
      - ROS (Robot Operating System)
      - MNE Python (EEG Signal Processing)

  - category: Control Systems & Algorithms
    tools:
      - Inverse Kinematics
      - Kinematic Modelling (PSS, PSU, Four-Bar Linkages)
      - Real-Time Control Systems
      - Brain-Computer Interface (BCI) Development
      - Signal Processing & Classification (EEG Data)

  - category: Prototyping & Fabrication
    tools:
      - 3D Printing (Stratasys PolyJet, FDM)
      - Rapid Prototyping
      - Laser Cutting
      - Lead Screw Mechanism Design

  - category: Human-Centered Design
    tools:
      - Assistive Technology Design
      - Ergonomics & Comfort Optimization
      - Human-Computer Interaction (HCI)

  - category: Interdisciplinary Knowledge
    tools:
      - Neurophysiology & EEG Signal Analysis
      - Systems Physiology (Musculoskeletal, Endocrine, Neuroscience)
      - Medical Device Development & Regulatory Compliance

  - category: Business & Entrepreneurship
    tools:
      - Medical Device Entrepreneurship
      - Product Development Lifecycle
      - Intellectual Property & Patent Analysis
      - Startup Operations & Business Strategy

  - category: Additional Technical Skills
    tools:
      - Textile Design & Fabric Integration
      - Data Analysis & Visualization
      - Simulation Software (URSim for Robotic Arms)
      - Machine Learning for Signal Classification

# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
#formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
